use_frameworks!

target 'AsyncSocket_Example' do
  pod 'AsyncSocket', :path => '../'

  target 'AsyncSocket_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
